runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored

service: cloudmine-amazon

runtime_config:
   jdk: openjdk8
   server: jetty9

automatic_scaling:
  min_num_instances: ${module.cloudmine-amazon.instancesMin}
  max_num_instances: ${module.cloudmine-amazon.instancesMax}
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

resources:
  cpu: 1
  memory_gb: 3

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 20
  timeout_sec: 19
  failure_threshold: 4
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 20
  timeout_sec: 19
  failure_threshold: 4
  success_threshold: 2
  app_start_timeout_sec: 240